Models/CategoryModel.cs
using Nop.Web.Framework.Models;

namespace Nop.Plugin.Mesut.ProductPriceManager.Models;

public record CategoryModel : BaseNopEntityModel
{
    public string Name { get; set; }
}

Models/ConfigurationModel.cs
using System;
using Nop.Web.Framework.Mvc.ModelBinding;

namespace Nop.Plugin.Mesut.ProductPriceManager.Models;

public class ConfigurationModel
{
    [NopResourceDisplayName("Plugins.Mesut.ProductPriceManager.Fields.SelectedCategories")]
    public int[] SelectedCategories { get; set; } = Array.Empty<int>();

    [NopResourceDisplayName("Plugins.Mesut.ProductPriceManager.Fields.SelectedManufacturers")]
    public int[] SelectedManufacturers { get; set; } = Array.Empty<int>();
    public string PriceAction { get; set; }
    public decimal Percentage { get; set; }
}

Models/ManufacturerModel.cs
using Nop.Web.Framework.Models;

namespace Nop.Plugin.Mesut.ProductPriceManager.Models;

public record ManufacturerModel : BaseNopEntityModel
{
    public string Name { get; set; }
}

Controllers/ProductPriceManagerController.cs
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Nop.Plugin.Mesut.ProductPriceManager.Models;
using Nop.Plugin.Mesut.ProductPriceManager.Services.Abstract;
using Nop.Services.Localization;
using Nop.Services.Messages;
using Nop.Web.Framework;
using Nop.Web.Framework.Controllers;
using Nop.Web.Framework.Mvc.Filters;

namespace Nop.Plugin.Mesut.ProductPriceManager.Controllers;

[AuthorizeAdmin]
[Area(AreaNames.Admin)]
[AutoValidateAntiforgeryToken]
public class ProductPriceManagerController : BasePluginController
{
    #region Fields
    private readonly IProductPriceService _productPriceService;
    private readonly INotificationService _notificationService;
    private readonly ILocalizationService _localizationService;
    #endregion

    #region Ctor
    public ProductPriceManagerController(IProductPriceService productPriceService, INotificationService notificationService, ILocalizationService localizationService)
    {
        _productPriceService = productPriceService;
        _notificationService = notificationService;
        _localizationService = localizationService;
    }
    #endregion

    #region Methods

    public IActionResult Configure()
    {
        return View("~/Plugins/Mesut.ProductPriceManager/Views/Configure.cshtml", new ConfigurationModel());
    }

    [HttpPost]
    public async Task<IActionResult> Configure(ConfigurationModel model)
    {
        await _productPriceService.UpdateProductPricesByManufacturersAsync(
                                    model.SelectedManufacturers,
                                    model.PriceAction == "IncreasePrices",
                                    model.Percentage);

        await _productPriceService.UpdateProductPricesByCategoriesAsync(
                                    model.SelectedCategories,
                                    model.PriceAction == "IncreasePrices",
                                    model.Percentage);
        _notificationService.SuccessNotification("Product prices updated succesfully");

        return View("~/Plugins/Mesut.ProductPriceManager/Views/Configure.cshtml", model);
    }
    #endregion
}

Views/Configure.cshtml
@model ConfigurationModel
@inject ICategoryService categoryService;
@inject IManufacturerService manufacturerService;
@{
    Layout = "_ConfigurePlugin";
    var categories = await categoryService.GetAllCategoriesAsync();
    var categoryModels = categories.Select(x => new CategoryModel { Id = x.Id, Name = x.Name });
    var manufacturers = await manufacturerService.GetAllManufacturersAsync();
    var manufacturerModels = manufacturers.Select(x => new ManufacturerModel { Id = x.Id, Name = x.Name });
}
<form asp-controller="ProductPriceManager" asp-action="Configure" method="post">
    <div class="form-group row">
        <div class="col-md-3 requirement-label-col">
            <nop-label asp-for="SelectedManufacturers" />
        </div>
        <div class="col-md-9 requirement-data-col">
            <div class="requirement-data-input">
                <select asp-for="SelectedManufacturers" 
                        asp-items="new SelectList(@manufacturerModels, 
                                    nameof(ManufacturerModel.Id), 
                                    nameof(ManufacturerModel.Name))" 
                        class="form-control" 
                        multiple></select>
            </div>
        </div>
    </div>
    <div class="form-group row">
        <div class="col-md-3 requirement-label-col">
            <nop-label asp-for="SelectedCategories" />
        </div>
        <div class="col-md-9 requirement-data-col">
            <div class="requirement-data-input">
                <select asp-for="SelectedCategories" 
                        asp-items="new SelectList(@categoryModels, 
                                nameof(CategoryModel.Id), 
                                nameof(CategoryModel.Name))" 
                        class="form-control"
                        multiple></select>
            </div>
        </div>
    </div>
    <div class="form-group row">
        <div class="col-md-3 requirement-label-col">
            <label for="increasePrices">Increase Prices</label>
        </div>
        <div class="col-md-9 requirement-data-col">
            <div class="requirement-data-input">
                <input type="radio" 
                    id="increasePrices" 
                    name="priceAction" 
                    value="IncreasePrices">
            </div>
        </div>
    </div>
    <div class="form-group row">
        <div class="col-md-3 requirement-label-col">
            <label for="reducePrices">Reduce Prices</label>
        </div>
        <div class="col-md-9 requirement-data-col">
            <div class="requirement-data-input">
                <input type="radio" 
                    id="reducePrices" 
                    name="priceAction" 
                    value="ReducePrices">
            </div>
        </div>
    </div>

    <div class="form-group row">
        <div class="col-md-3 requirement-label-col">
            <label for="percentage">Percentage (0-100)</label>
        </div>
        <div class="col-md-9 requirement-data-col">
            <div class="requirement-data-input">
                <input type="number" 
                    id="percentage" 
                    name="Percentage" 
                    min="1" 
                    max="999"
                    value="@Model.Percentage"/>
            </div>
        </div>
    </div>
    <button type="submit" class="btn btn-primary">Submit</button>
</form>